/* Generated from tokens.json by scripts/gen-css.mjs — edit tokens.json, never this file. */

export const WARD_VERSION = "0.2.0";
export type ChipRole = 'gate' | 'system' | 'write' | 'drift' | 'done' | 'attention' | 'failed' | 'pending' | 'running' | 'warn' | 'meta' | 'soft' | 'quiet';
export type StreamStep = 1 | 2 | 3 | 4 | 5 | 6;
export const CHIP_ROLES = ["gate","system","write","drift","done","attention","failed","pending","running","warn","meta","soft","quiet","stream"] as const;
export const STREAM_STEPS = [1,2,3,4,5,6] as const;
export const validatedStreamSteps = [1,2,3] as const;
export type ValidatedStreamStep = (typeof validatedStreamSteps)[number];
export type MarkerKind = 'stream' | 'green' | 'blue' | 'orange' | 'red' | 'amber' | 'neutral' | 'greenFill' | 'orangeFill';
export type MarkerSize = 6 | 8 | 9 | 14;
export const LIVE_EVENT_TYPES = ["run.started","run.step","run.finding","run.finished","item.moved","item.updated","snapshot","heartbeat"] as const;
export type LiveEventType = (typeof LIVE_EVENT_TYPES)[number];

export const v = {
  color: {
    bg: 'var(--ward-color-bg)',
    surface: 'var(--ward-color-surface)',
    surface2: 'var(--ward-color-surface2)',
    line: 'var(--ward-color-line)',
    line2: 'var(--ward-color-line2)',
    text: 'var(--ward-color-text)',
    muted: 'var(--ward-color-muted)',
    faint: 'var(--ward-color-faint)',
    blue: 'var(--ward-color-blue)',
    blueSoft: 'var(--ward-color-blueSoft)',
    runningTint: 'var(--ward-color-runningTint)',
    green: 'var(--ward-color-green)',
    orange: 'var(--ward-color-orange)',
    amber: 'var(--ward-color-amber)',
    red: 'var(--ward-color-red)',
    warnInk: 'var(--ward-color-warnInk)',
    warnSurface: 'var(--ward-color-warnSurface)',
    warnLine: 'var(--ward-color-warnLine)',
    console: 'var(--ward-color-console)',
    consoleInk: 'var(--ward-color-consoleInk)',
    consoleWarn: 'var(--ward-color-consoleWarn)',
    consoleOk: 'var(--ward-color-consoleOk)',
    consoleFaint: 'var(--ward-color-consoleFaint)',
    deep: 'var(--ward-color-deep)',
    overcapTint: 'var(--ward-color-overcapTint)',
    scrim: 'var(--ward-color-scrim)',
    greenFill: 'var(--ward-color-greenFill)',
    orangeFill: 'var(--ward-color-orangeFill)',
    consoleInfo: 'var(--ward-color-consoleInfo)',
    consoleDim: 'var(--ward-color-consoleDim)',
    line3: 'var(--ward-color-line3)',
    ink2: 'var(--ward-color-ink2)',
    surface3: 'var(--ward-color-surface3)',
  },
  chip: {
    gate: {
      bg: 'var(--ward-chip-gate-bg)',
      fg: 'var(--ward-chip-gate-fg)',
      line: 'var(--ward-chip-gate-line)',
    },
    system: {
      bg: 'var(--ward-chip-system-bg)',
      fg: 'var(--ward-chip-system-fg)',
      line: 'var(--ward-chip-system-line)',
    },
    write: {
      bg: 'var(--ward-chip-write-bg)',
      fg: 'var(--ward-chip-write-fg)',
      line: 'var(--ward-chip-write-line)',
    },
    drift: {
      bg: 'var(--ward-chip-drift-bg)',
      fg: 'var(--ward-chip-drift-fg)',
      line: 'var(--ward-chip-drift-line)',
    },
    done: {
      bg: 'var(--ward-chip-done-bg)',
      fg: 'var(--ward-chip-done-fg)',
      line: 'var(--ward-chip-done-line)',
    },
    attention: {
      bg: 'var(--ward-chip-attention-bg)',
      fg: 'var(--ward-chip-attention-fg)',
      line: 'var(--ward-chip-attention-line)',
    },
    failed: {
      bg: 'var(--ward-chip-failed-bg)',
      fg: 'var(--ward-chip-failed-fg)',
      line: 'var(--ward-chip-failed-line)',
    },
    pending: {
      bg: 'var(--ward-chip-pending-bg)',
      fg: 'var(--ward-chip-pending-fg)',
      line: 'var(--ward-chip-pending-line)',
    },
    running: {
      bg: 'var(--ward-chip-running-bg)',
      fg: 'var(--ward-chip-running-fg)',
      line: 'var(--ward-chip-running-line)',
    },
    warn: {
      bg: 'var(--ward-chip-warn-bg)',
      fg: 'var(--ward-chip-warn-fg)',
      line: 'var(--ward-chip-warn-line)',
    },
    meta: {
      bg: 'var(--ward-chip-meta-bg)',
      fg: 'var(--ward-chip-meta-fg)',
      line: 'var(--ward-chip-meta-line)',
    },
    soft: {
      bg: 'var(--ward-chip-soft-bg)',
      fg: 'var(--ward-chip-soft-fg)',
      line: 'var(--ward-chip-soft-line)',
    },
    quiet: {
      bg: 'var(--ward-chip-quiet-bg)',
      fg: 'var(--ward-chip-quiet-fg)',
      line: 'var(--ward-chip-quiet-line)',
    },
  },
  space: {
    s1: 'var(--ward-space-1)',
    s2: 'var(--ward-space-2)',
    s3: 'var(--ward-space-3)',
    s4: 'var(--ward-space-4)',
    s5: 'var(--ward-space-5)',
    s6: 'var(--ward-space-6)',
    s7: 'var(--ward-space-7)',
    page: 'var(--ward-space-page)',
  },
  pad: {
    row: 'var(--ward-pad-row)',
    sessionCell: 'var(--ward-pad-sessionCell)',
    sessionTitle: 'var(--ward-pad-sessionTitle)',
    sessionHead: 'var(--ward-pad-sessionHead)',
    scopeTabs: 'var(--ward-pad-scopeTabs)',
    kv: 'var(--ward-pad-kv)',
    field: 'var(--ward-pad-field)',
    activity: 'var(--ward-pad-activity)',
    timeline: 'var(--ward-pad-timeline)',
    section: 'var(--ward-pad-section)',
    bar: 'var(--ward-pad-bar)',
    tabs: 'var(--ward-pad-tabs)',
    console: 'var(--ward-pad-console)',
    message: 'var(--ward-pad-message)',
    chip: 'var(--ward-pad-chip)',
    control: 'var(--ward-pad-control)',
    bandHead: 'var(--ward-pad-bandHead)',
    bandCell: 'var(--ward-pad-bandCell)',
    configRow: 'var(--ward-pad-configRow)',
    configHead: 'var(--ward-pad-configHead)',
    input: 'var(--ward-pad-input)',
    controlPrimary: 'var(--ward-pad-controlPrimary)',
    ruleRow: 'var(--ward-pad-ruleRow)',
    toolRow: 'var(--ward-pad-toolRow)',
    sectionBlock: 'var(--ward-pad-sectionBlock)',
    page: 'var(--ward-pad-page)',
    pageHeader: 'var(--ward-pad-pageHeader)',
    boardHead: 'var(--ward-pad-boardHead)',
    boardColumn: 'var(--ward-pad-boardColumn)',
    workCard: 'var(--ward-pad-workCard)',
    trace: 'var(--ward-pad-trace)',
    metricCell: 'var(--ward-pad-metricCell)',
    railSection: 'var(--ward-pad-railSection)',
    sidebarBrand: 'var(--ward-pad-sidebarBrand)',
    sidebarNav: 'var(--ward-pad-sidebarNav)',
    sidebarGroup: 'var(--ward-pad-sidebarGroup)',
    sidebarAgent: 'var(--ward-pad-sidebarAgent)',
    sidebarFoot: 'var(--ward-pad-sidebarFoot)',
    sidebarFootList: 'var(--ward-pad-sidebarFootList)',
    drawerHead: 'var(--ward-pad-drawerHead)',
    drawerSummary: 'var(--ward-pad-drawerSummary)',
    drawerBlock: 'var(--ward-pad-drawerBlock)',
    drawerKv: 'var(--ward-pad-drawerKv)',
    caseHead: 'var(--ward-pad-caseHead)',
    caseCriteria: 'var(--ward-pad-caseCriteria)',
    caseHistory: 'var(--ward-pad-caseHistory)',
    railBlock: 'var(--ward-pad-railBlock)',
    railList: 'var(--ward-pad-railList)',
    intakeTurn: 'var(--ward-pad-intakeTurn)',
    placementList: 'var(--ward-pad-placementList)',
    policyRow: 'var(--ward-pad-policyRow)',
    policyCallout: 'var(--ward-pad-policyCallout)',
    adminCard: 'var(--ward-pad-adminCard)',
    runbookStep: 'var(--ward-pad-runbookStep)',
    gateRung: 'var(--ward-pad-gateRung)',
    criterion: 'var(--ward-pad-criterion)',
    resolvePath: 'var(--ward-pad-resolvePath)',
    stageColumn: 'var(--ward-pad-stageColumn)',
    stageFoot: 'var(--ward-pad-stageFoot)',
    streamCell: 'var(--ward-pad-streamCell)',
    streamHead: 'var(--ward-pad-streamHead)',
    streamFoot: 'var(--ward-pad-streamFoot)',
    modalHead: 'var(--ward-pad-modalHead)',
    modalBody: 'var(--ward-pad-modalBody)',
    modalSection: 'var(--ward-pad-modalSection)',
    modalInput: 'var(--ward-pad-modalInput)',
    stageRow: 'var(--ward-pad-stageRow)',
    choiceCard: 'var(--ward-pad-choiceCard)',
    swatchRow: 'var(--ward-pad-swatchRow)',
    addStage: 'var(--ward-pad-addStage)',
    fieldCell: 'var(--ward-pad-fieldCell)',
    skeletonColumn: 'var(--ward-pad-skeletonColumn)',
  },
  gap: {
    row: 'var(--ward-gap-row)',
    section: 'var(--ward-gap-section)',
    bar: 'var(--ward-gap-bar)',
    tabs: 'var(--ward-gap-tabs)',
    field: 'var(--ward-gap-field)',
    activity: 'var(--ward-gap-activity)',
    timeline: 'var(--ward-gap-timeline)',
    console: 'var(--ward-gap-console)',
    message: 'var(--ward-gap-message)',
    intakeTurn: 'var(--ward-gap-intakeTurn)',
    intakeThread: 'var(--ward-gap-intakeThread)',
    readyList: 'var(--ward-gap-readyList)',
    policyRow: 'var(--ward-gap-policyRow)',
    policyState: 'var(--ward-gap-policyState)',
    policyCallout: 'var(--ward-gap-policyCallout)',
    policyGroup: 'var(--ward-gap-policyGroup)',
    policyStack: 'var(--ward-gap-policyStack)',
    adminCard: 'var(--ward-gap-adminCard)',
    adminAside: 'var(--ward-gap-adminAside)',
    adminGrid: 'var(--ward-gap-adminGrid)',
    envGrid: 'var(--ward-gap-envGrid)',
    deployStack: 'var(--ward-gap-deployStack)',
    runbookStep: 'var(--ward-gap-runbookStep)',
    band: 'var(--ward-gap-band)',
    configRow: 'var(--ward-gap-configRow)',
    configName: 'var(--ward-gap-configName)',
    ruleRow: 'var(--ward-gap-ruleRow)',
    toolRow: 'var(--ward-gap-toolRow)',
    sectionBlock: 'var(--ward-gap-sectionBlock)',
    sample: 'var(--ward-gap-sample)',
    trace: 'var(--ward-gap-trace)',
    traceHead: 'var(--ward-gap-traceHead)',
    traceBody: 'var(--ward-gap-traceBody)',
    traceDotTop: 'var(--ward-gap-traceDotTop)',
    metricCell: 'var(--ward-gap-metricCell)',
    sidebarBrand: 'var(--ward-gap-sidebarBrand)',
    sidebarAgent: 'var(--ward-gap-sidebarAgent)',
    sidebarDot: 'var(--ward-gap-sidebarDot)',
    boardColumn: 'var(--ward-gap-boardColumn)',
    drawerBlock: 'var(--ward-gap-drawerBlock)',
    resolveList: 'var(--ward-gap-resolveList)',
    entryBody: 'var(--ward-gap-entryBody)',
    criterionMark: 'var(--ward-gap-criterionMark)',
    entryNode: 'var(--ward-gap-entryNode)',
    stageColumn: 'var(--ward-gap-stageColumn)',
    stageHead: 'var(--ward-gap-stageHead)',
    stageTag: 'var(--ward-gap-stageTag)',
    streamCell: 'var(--ward-gap-streamCell)',
    streamChain: 'var(--ward-gap-streamChain)',
    agentCard: 'var(--ward-gap-agentCard)',
    agentTags: 'var(--ward-gap-agentTags)',
    gatePanel: 'var(--ward-gap-gatePanel)',
    reviewerList: 'var(--ward-gap-reviewerList)',
    reviewer: 'var(--ward-gap-reviewer)',
    terminalCard: 'var(--ward-gap-terminalCard)',
    formLabel: 'var(--ward-gap-formLabel)',
    formStack: 'var(--ward-gap-formStack)',
    swatch: 'var(--ward-gap-swatch)',
    stageList: 'var(--ward-gap-stageList)',
    choiceBody: 'var(--ward-gap-choiceBody)',
    modalFooter: 'var(--ward-gap-modalFooter)',
    fieldCell: 'var(--ward-gap-fieldCell)',
    fieldGridRow: 'var(--ward-gap-fieldGridRow)',
    fieldGridCol: 'var(--ward-gap-fieldGridCol)',
    grouping: 'var(--ward-gap-grouping)',
    configSub: 'var(--ward-gap-configSub)',
    skeleton: 'var(--ward-gap-skeleton)',
    effects: 'var(--ward-gap-effects)',
  },
  width: {
    max: 'var(--ward-width-max)',
    drawer: 'var(--ward-width-drawer)',
    dryrun: 'var(--ward-width-dryrun)',
    preview: 'var(--ward-width-preview)',
    colFloor: 'var(--ward-width-colFloor)',
    sessionResolved: 'var(--ward-width-sessionResolved)',
    sessionCost: 'var(--ward-width-sessionCost)',
    sessionActivity: 'var(--ward-width-sessionActivity)',
    sessionState: 'var(--ward-width-sessionState)',
    switchTrack: 'var(--ward-width-switchTrack)',
    colCredId: 'var(--ward-width-colCredId)',
    colClass: 'var(--ward-width-colClass)',
    colTier: 'var(--ward-width-colTier)',
    colNext: 'var(--ward-width-colNext)',
    colState: 'var(--ward-width-colState)',
    colServer: 'var(--ward-width-colServer)',
    colTools: 'var(--ward-width-colTools)',
    colPin: 'var(--ward-width-colPin)',
    colConn: 'var(--ward-width-colConn)',
    overlayWide: 'var(--ward-width-overlayWide)',
    form: 'var(--ward-width-form)',
    drawerKey: 'var(--ward-width-drawerKey)',
    maxWide: 'var(--ward-width-maxWide)',
    sidebar: 'var(--ward-width-sidebar)',
    keyCol: 'var(--ward-width-keyCol)',
    keyColWide: 'var(--ward-width-keyColWide)',
    bandHead: 'var(--ward-width-bandHead)',
    rail: 'var(--ward-width-rail)',
    configHandle: 'var(--ward-width-configHandle)',
    configLabel: 'var(--ward-width-configLabel)',
    toolName: 'var(--ward-width-toolName)',
    configCap: 'var(--ward-width-configCap)',
    configShown: 'var(--ward-width-configShown)',
    gateTag: 'var(--ward-width-gateTag)',
    gateActor: 'var(--ward-width-gateActor)',
    stageColumn: 'var(--ward-width-stageColumn)',
    streamName: 'var(--ward-width-streamName)',
    streamAgents: 'var(--ward-width-streamAgents)',
    streamPolicy: 'var(--ward-width-streamPolicy)',
    policyControl: 'var(--ward-width-policyControl)',
    roleGroup: 'var(--ward-width-roleGroup)',
    rolePeople: 'var(--ward-width-rolePeople)',
    roleVia: 'var(--ward-width-roleVia)',
    roleIndent: 'var(--ward-width-roleIndent)',
    personIndent: 'var(--ward-width-personIndent)',
    adminAside: 'var(--ward-width-adminAside)',
    streamFlight: 'var(--ward-width-streamFlight)',
    streamIndent: 'var(--ward-width-streamIndent)',
    streamEdge: 'var(--ward-width-streamEdge)',
    streamKey: 'var(--ward-width-streamKey)',
    colourPick: 'var(--ward-width-colourPick)',
  },
  height: {
    control: 'var(--ward-height-control)',
    controlSm: 'var(--ward-height-controlSm)',
    card: 'var(--ward-height-card)',
    cardRow: 'var(--ward-height-cardRow)',
    touch: 'var(--ward-height-touch)',
    topbar: 'var(--ward-height-topbar)',
    identityChip: 'var(--ward-height-identityChip)',
    chart: 'var(--ward-height-chart)',
    switchTrack: 'var(--ward-height-switchTrack)',
    switchThumb: 'var(--ward-height-switchThumb)',
    bar: 'var(--ward-height-bar)',
    mark: 'var(--ward-height-mark)',
    app: 'var(--ward-height-app)',
    traceDot: 'var(--ward-height-traceDot)',
    brandMark: 'var(--ward-height-brandMark)',
    agentDot: 'var(--ward-height-agentDot)',
    reviewerMark: 'var(--ward-height-reviewerMark)',
    swatch: 'var(--ward-height-swatch)',
    radio: 'var(--ward-height-radio)',
    skeletonBar: 'var(--ward-height-skeletonBar)',
  },
  size: {
    marker6: 'var(--ward-size-marker6)',
    marker8: 'var(--ward-size-marker8)',
    marker9: 'var(--ward-size-marker9)',
    marker14: 'var(--ward-size-marker14)',
  },
  radius: 'var(--ward-radius)',
  border: 'var(--ward-border)',
  underline: 'var(--ward-underline)',
  shadow: { overlay: 'var(--ward-shadow-overlay)' },
  type: {
    h1: 'var(--ward-type-h1)',
    h1Tracking: 'var(--ward-type-h1-tracking)',
    title: 'var(--ward-type-title)',
    stat: 'var(--ward-type-stat)',
    statNumeric: 'var(--ward-type-stat-numeric)',
    body: 'var(--ward-type-body)',
    secondary: 'var(--ward-type-secondary)',
    meta: 'var(--ward-type-meta)',
    control: 'var(--ward-type-control)',
    monoId: 'var(--ward-type-monoId)',
    monoIdNumeric: 'var(--ward-type-monoId-numeric)',
    chip: 'var(--ward-type-chip)',
    chipTracking: 'var(--ward-type-chip-tracking)',
    chipTransform: 'var(--ward-type-chip-transform)',
    micro: 'var(--ward-type-micro)',
    microTracking: 'var(--ward-type-micro-tracking)',
    microTransform: 'var(--ward-type-micro-transform)',
    colHead: 'var(--ward-type-colHead)',
    colHeadTracking: 'var(--ward-type-colHead-tracking)',
    colHeadTransform: 'var(--ward-type-colHead-transform)',
    rowName: 'var(--ward-type-rowName)',
    rowNote: 'var(--ward-type-rowNote)',
    inputText: 'var(--ward-type-inputText)',
    inputStrong: 'var(--ward-type-inputStrong)',
    stateLabel: 'var(--ward-type-stateLabel)',
    ruleCond: 'var(--ward-type-ruleCond)',
    ruleAct: 'var(--ward-type-ruleAct)',
    toolName: 'var(--ward-type-toolName)',
    toolScope: 'var(--ward-type-toolScope)',
    sampleTitle: 'var(--ward-type-sampleTitle)',
    traceTitle: 'var(--ward-type-traceTitle)',
    traceDetail: 'var(--ward-type-traceDetail)',
    handleMark: 'var(--ward-type-handleMark)',
    pageTitle: 'var(--ward-type-pageTitle)',
    pageTitleTracking: 'var(--ward-type-pageTitle-tracking)',
    bandTitle: 'var(--ward-type-bandTitle)',
    bandTitleTracking: 'var(--ward-type-bandTitle-tracking)',
    cellTitle: 'var(--ward-type-cellTitle)',
    cardTitle: 'var(--ward-type-cardTitle)',
    keyCol: 'var(--ward-type-keyCol)',
    keyColTracking: 'var(--ward-type-keyCol-tracking)',
    keyColTransform: 'var(--ward-type-keyCol-transform)',
    kvValue: 'var(--ward-type-kvValue)',
    consoleLine: 'var(--ward-type-consoleLine)',
    monoText: 'var(--ward-type-monoText)',
    useText: 'var(--ward-type-useText)',
    tabLabel: 'var(--ward-type-tabLabel)',
    bandNote: 'var(--ward-type-bandNote)',
    modalTitle: 'var(--ward-type-modalTitle)',
    modalTitleTracking: 'var(--ward-type-modalTitle-tracking)',
    choiceNote: 'var(--ward-type-choiceNote)',
    inputMono: 'var(--ward-type-inputMono)',
    cellBody: 'var(--ward-type-cellBody)',
    markGlyph: 'var(--ward-type-markGlyph)',
    microHead: 'var(--ward-type-microHead)',
    microHeadTracking: 'var(--ward-type-microHead-tracking)',
    microHeadTransform: 'var(--ward-type-microHead-transform)',
    brandMark: 'var(--ward-type-brandMark)',
    brandMarkTracking: 'var(--ward-type-brandMark-tracking)',
    navAction: 'var(--ward-type-navAction)',
    swatchName: 'var(--ward-type-swatchName)',
    agentActive: 'var(--ward-type-agentActive)',
    boardTitle: 'var(--ward-type-boardTitle)',
    boardTitleTracking: 'var(--ward-type-boardTitle-tracking)',
    columnLabel: 'var(--ward-type-columnLabel)',
    columnCount: 'var(--ward-type-columnCount)',
    columnCountNumeric: 'var(--ward-type-columnCount-numeric)',
    overCapCount: 'var(--ward-type-overCapCount)',
    overCapCountNumeric: 'var(--ward-type-overCapCount-numeric)',
    workTitle: 'var(--ward-type-workTitle)',
    overCapNote: 'var(--ward-type-overCapNote)',
    caseTitle: 'var(--ward-type-caseTitle)',
    caseTitleTracking: 'var(--ward-type-caseTitle-tracking)',
    costTotal: 'var(--ward-type-costTotal)',
    costTotalNumeric: 'var(--ward-type-costTotal-numeric)',
    entryStage: 'var(--ward-type-entryStage)',
    sessionTitle: 'var(--ward-type-sessionTitle)',
    ruleNote: 'var(--ward-type-ruleNote)',
    costCeiling: 'var(--ward-type-costCeiling)',
    drawerTitle: 'var(--ward-type-drawerTitle)',
    stageName: 'var(--ward-type-stageName)',
    agentName: 'var(--ward-type-agentName)',
    cardNote: 'var(--ward-type-cardNote)',
    gateNote: 'var(--ward-type-gateNote)',
    reviewerName: 'var(--ward-type-reviewerName)',
    reviewerMark: 'var(--ward-type-reviewerMark)',
    terminalCount: 'var(--ward-type-terminalCount)',
    terminalCountNumeric: 'var(--ward-type-terminalCount-numeric)',
    tag: 'var(--ward-type-tag)',
    tagTracking: 'var(--ward-type-tag-tracking)',
    tagTransform: 'var(--ward-type-tag-transform)',
    policyKey: 'var(--ward-type-policyKey)',
    stageFoot: 'var(--ward-type-stageFoot)',
    streamName: 'var(--ward-type-streamName)',
    cellSub: 'var(--ward-type-cellSub)',
    sampleValue: 'var(--ward-type-sampleValue)',
    skeletonLabel: 'var(--ward-type-skeletonLabel)',
    previewNote: 'var(--ward-type-previewNote)',
    effectText: 'var(--ward-type-effectText)',
    scopeName: 'var(--ward-type-scopeName)',
    scopeNameTracking: 'var(--ward-type-scopeName-tracking)',
    personName: 'var(--ward-type-personName)',
  },
  motion: {
    fast: 'var(--ward-motion-fast)',
    flash: 'var(--ward-motion-flash)',
    reveal: 'var(--ward-motion-reveal)',
    tick: 'var(--ward-motion-tick)',
    patience: 'var(--ward-motion-patience)',
  },
  live: {
    heartbeat: 'var(--ward-live-heartbeat)',
    reconnectMax: 'var(--ward-live-reconnectMax)',
    staleAfter: 'var(--ward-live-staleAfter)',
    poll: 'var(--ward-live-poll)',
  },
} as const;

export const ms = {
  fast: 120,
  flash: 300,
  reveal: 320,
  tick: 1000,
  patience: 800,
  heartbeat: 15000,
  poll: 15000,
  reconnectMax: 30000,
  staleAfter: 45000,
  reconnectBase: 1000,
  load: 800,
} as const;

export function stream(step: StreamStep) {
  return {
    id: `var(--ward-stream-${step}-id)`,
    chip: `var(--ward-stream-${step}-chip)`,
    chipText: `var(--ward-stream-${step}-chipText)`,
  } as const;
}

export function isStreamStep(step: number): step is StreamStep {
  return (STREAM_STEPS as readonly number[]).includes(step);
}

export function isValidatedStreamStep(step: number): step is ValidatedStreamStep {
  return (validatedStreamSteps as readonly number[]).includes(step);
}

export function streamVars(step: number): Record<string, string> {
  if (!isStreamStep(step)) throw new Error('unvalidated stream step');
  return { '--stream': `var(--ward-stream-${step}-chip)`, '--streamText': `var(--ward-stream-${step}-chipText)`, '--streamId': `var(--ward-stream-${step}-id)` };
}

export function streamChip(step: number): string {
  if (!isStreamStep(step)) throw new Error('unvalidated stream step');
  return `var(--ward-stream-${step}-chip)`;
}
